AssetTrakingSystemApp/AssetTrakingSystemApp/Controllers/ProductCategorisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTrakingSystemApp.BLL;
using AssetTrakingSystemApp.Models;


namespace AssetTrakingSystemApp.Controllers
{
    public class ProductCategorisController : Controller
    {
        ProductCategoriesManager productCategoriesManager=new ProductCategoriesManager();
        SubCategoryManager subCategoryManager=new SubCategoryManager();
        CategorySetupManager categorySetupManager=new CategorySetupManager();
        GeneralCategoryManager generalCategoryManager=new GeneralCategoryManager();
        //
        // GET: /ProductCategoris/
        [HttpGet]
        public ActionResult Save()
        {
            List<ProductCategory> productCategories = productCategoriesManager.GetAll();
            ViewBag.ProducCategoriesList = productCategories;
            List<SubCategory> subCategories = subCategoryManager.GetAll();
            ViewBag.SubCategoriesList = subCategories;
            List<CategorySetup> categorySetups = categorySetupManager.GetAll();
            ViewBag.ProducCategoriesList = categorySetups;
            List<GeneralCatagory> generalCatagories = generalCategoryManager.GetAll();
            ViewBag.GeneralCategorisList = generalCatagories;
            return View();
        }
        [HttpPost]
        public ActionResult Save(ProductCategory productCategory)
        {
            List<ProductCategory> productCategories = productCategoriesManager.GetAll();
            ViewBag.ProducCategoriesList = productCategories;
            List<SubCategory> subCategories = subCategoryManager.GetAll();
            ViewBag.SubCategoriesList = subCategories;
            List<CategorySetup> categorySetups = categorySetupManager.GetAll();
            ViewBag.ProducCategoriesList = categorySetups;
            List<GeneralCatagory> generalCatagories = generalCategoryManager.GetAll();
            ViewBag.GeneralCategorisList = generalCatagories;

            if (productCategory.Name == null || productCategory.Code == null || productCategory.GeneralCategoryId == 0 ||
                productCategory.CategorySetupId == 0 || productCategory.SubCategoryId == 0)
            {
                ViewBag.message = "Input field is requird";
            }
            else
            {
                if (productCategory.Code.Length > 5)
                {
                    ViewBag.message = "code lenth is greater than 5 which is not allowed";
                }
                else
                {
                    bool isCodeExist = productCategoriesManager.isCodeExist(productCategory.Code);
                    if (isCodeExist)
                    {
                        ViewBag.message = "Code is already exist";
                    }
                    else
                    {
                        bool save = productCategoriesManager.Add(productCategory);
                        if (save)
                        {
                            ViewBag.message = "Save successfull";
                        }
                        else
                        {
                            ViewBag.message = "Save failed";
                        }
                    }
                }
            }
         
            
            return View();
        }
        public JsonResult GetCategorySetupIdByGeneralCategoryId(int generalCategoryId)
        {
            var CategorySetupIdLists = categorySetupManager.GetCategorySetupIdByGeneralCategoryId(generalCategoryId);
            return Json(CategorySetupIdLists, JsonRequestBehavior.AllowGet);
        }
	}
}

AssetTrakingSystemApp/AssetTrakingSystemApp/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTrakingSystemApp.BLL;
using AssetTrakingSystemApp.Models;

namespace AssetTrakingSystemApp.Controllers
{
    public class SubCategoryController : Controller
    {
        SubCategoryManager subCategoryManager=new SubCategoryManager();
       GeneralCategoryManager generalCategoryManager=new GeneralCategoryManager();
        CategorySetupManager categorySetupManager=new CategorySetupManager();
        //
        // GET: /SubCategory/
        [HttpGet]
        public ActionResult Save()
        {
            List<GeneralCatagory> generalCatagories = generalCategoryManager.GetAll();
            ViewBag.GeneralcategoryList = generalCatagories;
            List<CategorySetup> categorySetups = categorySetupManager.GetAll();
            ViewBag.CategorySetupList = categorySetups;
            List<SubCategory> subCategories = subCategoryManager.GetAll();
            ViewBag.SubCategoryList = subCategories;
            return View();
        }
        [HttpPost]
        public ActionResult Save(SubCategory subCategory)
        {
            List<SubCategory> subCategories = subCategoryManager.GetAll();
            ViewBag.SubCategoryList = subCategories;
            List<GeneralCatagory> generalCatagories = generalCategoryManager.GetAll();
            ViewBag.GeneralcategoryList = generalCatagories;
             List<CategorySetup> categorySetups = categorySetupManager.GetAll();
            ViewBag.CategorySetupList = categorySetups;

            if (subCategory.Name == null || subCategory.Code == null || subCategory.CategorySetupId == 0 ||
                subCategory.GeneralCtegoryId == 0)
            {
                ViewBag.message = "input field is requird";
            }
            else
            {
                if (subCategory.Code.Length > 5)
                {
                    ViewBag.message = "Code lenth is greatr than 5 not allowed";
                }
                else
                {
                    bool IsCodeExist = subCategoryManager.isCodeExist(subCategory.Code);
                    if (IsCodeExist)
                    {
                        ViewBag.message = "code is already exist !";
                    }
                    else
                    {
                        bool Save = subCategoryManager.Add(subCategory);
                        if (Save)
                        {
                            ViewBag.message = "Save successfull";
                        }
                        else
                        {
                            ViewBag.message = "Save failed";
                        }
                    }
                }
            }

           
                
          
           
            return View();
        }

        public JsonResult GetCategorySetupIdByGeneralCategoryId(int generalCategoryId)
        {
            var CategorySetupIdLists = categorySetupManager.GetCategorySetupIdByGeneralCategoryId(generalCategoryId);
            return Json(CategorySetupIdLists, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSubCategoryIdByCategorySetupId(int CategorySetupId)
        {
            var subCategoriesLists = subCategoryManager.GetSubCategoryIdByCategorySetupId(CategorySetupId);
            return Json(subCategoriesLists, JsonRequestBehavior.AllowGet);
        }
	}
}

AssetTrakingSystemApp/AssetTrakingSystemApp/Views/ProductCategoris/Save.cshtml
@using AssetTrakingSystemApp.Models
@model AssetTrakingSystemApp.Models.ProductCategory

@{
    ViewBag.Title = "Save";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-info">Save Product details/Model details</h2>

@if (ViewBag.message != null)
{
    <h4 class="text-danger">@ViewBag.message</h4>
}

@using (Html.BeginForm())
{
    <div>
        @Html.LabelFor(c => c.GeneralCategoryId)
        <select class="form-control" id="GeneralCategoryId" name="GeneralCategoryId">
            <option>select..</option>
            @foreach (var sym in ((List<GeneralCatagory>) ViewBag.GeneralCategorisList))
            {
                <option value="@sym.Id">@sym.Name</option>
            }
        </select>
        @*@Html.DropDownListFor(c => c.GeneralCategoryId, new SelectList(ViewBag.GeneralCategorisList, "Id", "Name"))*@
        @Html.ValidationMessageFor(c => c.GeneralCategoryId)
    </div>
    <div>
        @Html.LabelFor(c => c.CategorySetupId)
        <select class="form-control" id="CategorySetupId" name="CategorySetupId">
            <option>Select..</option>
        </select>
        @Html.ValidationMessageFor(c => c.CategorySetupId)
    </div>

    <div>
        @Html.LabelFor(c => c.SubCategoryId)
        <select class="form-control" id="SubCategoryId" name="SubCategoryId">
            <option>select..</option>
        </select>
        @Html.ValidationMessageFor(c => c.SubCategoryId)
    </div>
    <div>
        @Html.LabelFor(c => c.Name)
        @Html.TextBoxFor(c => c.Name,new{@class="form-control"})
        @Html.ValidationMessageFor(c => c.Name)
    </div>
    <div>
        @Html.LabelFor(c => c.Code)
        @Html.TextBoxFor(c => c.Code,new{@class="form-control"})
        @Html.ValidationMessageFor(c => c.Code)
    </div>
    <div>
        @Html.LabelFor(c => c.ProductDescription)
        @Html.TextAreaFor(c => c.ProductDescription, new {@class = "form-control"})
        @Html.ValidationMessageFor(c => c.ProductDescription)

    </div>
    <br/>
    <div>
        <button class="btn-primary" type="submit">Save</button>
    </div>
    <br/><br/>
    
     @*<table class="table table-striped">
        <tr>
            <th>Name</th>
            <th>Code</th>
            

        </tr>
        @foreach (var org in ((List<ProductCategory>)ViewBag.ProducCategoriesList))
        {
            <tr>
                <td>@org.Name</td>
                <td>@org.Code</td>
              

            </tr>
        }

    </table>*@
 

}

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    $(document)
        .ready(function () {

            //for get Category setup

            $("#GeneralCategoryId")
                .change(function() {

                    var distId = $("#GeneralCategoryId").val();
                    $("#CategorySetupId").empty();
                    $("#SubCategoryId").empty();
                    var json = {
                        generalCategoryId: distId
                    };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetCategorySetupIdByGeneralCategoryId", "ProductCategoris")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),

                        success: function(data) {
                            $("#CategorySetupId").prepend('<option >select..</option>');
                            //alert(data);
                            $.each(data,
                                function(key, value) {
                                    //alert(key);

                                    $("#CategorySetupId").append('<option value=' + value.Id + '>' + value.Name + '</option>');


                                });
                        }
                    });
                });

            //for sub category 

            $("#CategorySetupId")
                .change(function () {

                    var distId = $("#CategorySetupId").val();
                    $("#SubCategoryId").empty();
                    var json = {
                        CategorySetupId: distId
                    };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetSubCategoryIdByCategorySetupId", "SubCategory")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),

                        success: function (data) {
                            $("#SubCategoryId").prepend('<option >select..</option>');
                            //alert(data);
                            $.each(data,
                                function (key, value) {
                                    //alert(key);

                                    $("#SubCategoryId").append('<option value=' + value.Id + '>' + value.Name + '</option>');


                                });
                        }
                    });
                });
        });
</script>