AssetTrakingSystemApp/AssetTrakingSystemApp/Controllers/AssetLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTrakingSystemApp.BLL;
using AssetTrakingSystemApp.Models;

namespace AssetTrakingSystemApp.Controllers
{
    public class AssetLocationController : Controller
    {
        OrganizationBranchManager orgManager=new OrganizationBranchManager();
        OrganizationManager manager=new OrganizationManager();
        AssetLocationManager assetmanager=new AssetLocationManager();
        //
        // GET: /AssetLocation/
        [HttpGet]
        public ActionResult Save()
        {

            List<Organization> organizations = manager.GetAll();
            ViewBag.organizationList = organizations.ToList();
            List<OrganizationBranch> organizationBranches = orgManager.OrganizationBranches();
            ViewBag.OrgBranchList = organizationBranches;
            List<AssetLocation> assetLocations = assetmanager.GetAll();
            ViewBag.AssetLocationList = assetLocations;
            return View();
        }
        [HttpPost]
        public ActionResult Save(AssetLocation assetLocation)
        {
            List<AssetLocation> assetLocations = assetmanager.GetAll();
            ViewBag.AssetLocationList = assetLocations;
            List<Organization> organizations = manager.GetAll();
            ViewBag.organizationList = organizations.ToList();
            List<OrganizationBranch> organizationBranches = orgManager.OrganizationBranches();
            ViewBag.OrgBranchList = organizationBranches;
            if (assetLocation.Name == null || assetLocation.ShortName == null || assetLocation.OrganigationId == 0 ||
                assetLocation.OrganigationId == 0)
            {
                ViewBag.message = "Input filed is requierd";
            }
            else
            {
                if (assetLocation.ShortName.Length > 5)
                {
                    ViewBag.message = "Short name filed is to be maximum 5 digit";
                }
                else
                {
                    bool IsShortNameExist = assetmanager.IsShortNameExist(assetLocation.ShortName);
                    if (IsShortNameExist)
                    {
                        ViewBag.message = "Short name is already exist !";

                    }
                    else
                    {
                        bool Save = assetmanager.Add(assetLocation);
                        if (Save)
                        {
                            ViewBag.message = "Save Location Successfull !";
                        }
                        else
                        {
                            ViewBag.message = "Save failed";
                        }
                    } 
                }
               
            }
           
            
            
            return View();
        }

        public JsonResult GetOrganizationBranchIdByOrganizationId(int organizationId)
        {
            var organaizationBranchLists = orgManager.GetOrganizationBranchIdByOrganizationId(organizationId);
            return Json(organaizationBranchLists, JsonRequestBehavior.AllowGet);
        }
	}
}

AssetTrakingSystemApp/AssetTrakingSystemApp/Controllers/CategorySetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTrakingSystemApp.BLL;
using AssetTrakingSystemApp.Models;

namespace AssetTrakingSystemApp.Controllers
{
    public class CategorySetupController : Controller
    {
        CategorySetupManager manager=new CategorySetupManager();
        GeneralCategoryManager generalCategoryManager=new GeneralCategoryManager();
        //
        // GET: /CategorySetup/
        [HttpGet]
        public ActionResult Save()
        {
            List<GeneralCatagory> generalCatagories = generalCategoryManager.GetAll();
            ViewBag.GeneralCategoryList = generalCatagories;
            List<CategorySetup> categorySetups = manager.GetAll();
            ViewBag.CategorySetupList = categorySetups;
            return View();
        }
        [HttpPost]
        public ActionResult Save(CategorySetup categorySetup)
        {
            List<GeneralCatagory> generalCatagories = generalCategoryManager.GetAll();
            ViewBag.GeneralCategoryList = generalCatagories;
            List<CategorySetup> categorySetups = manager.GetAll();
            ViewBag.CategorySetupList = categorySetups;
            if (categorySetup.Name == null || categorySetup.Code == null || categorySetup.GeneralCategoryId == 0)
            {
                ViewBag.message = "input field is requird";
            }
            else
            {
                if (categorySetup.Code.Length > 5)
                {
                    ViewBag.message = "Code lenth is greater than 5 not allowed";
                }
                else
                {
                    bool IscodeExist = manager.isCodeExist(categorySetup.Code);
                    if (IscodeExist)
                    {
                        ViewBag.message = "Code is already exist";
                    }
                    else
                    {
                        bool Save = manager.Add(categorySetup);
                        if (Save)
                        {
                            ViewBag.message = "Save successfull";
                        }
                        else
                        {
                            ViewBag.message = "Save failed";
                        }
                    }
                }
            }
            
         
            return View();
        }
	}
}

AssetTrakingSystemApp/AssetTrakingSystemApp/Controllers/GeneralCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTrakingSystemApp.BLL;
using AssetTrakingSystemApp.Models;

namespace AssetTrakingSystemApp.Controllers
{
    
    public class GeneralCategoryController : Controller
    {
        GeneralCategoryManager  manager=new GeneralCategoryManager();
        //
        // GET: /GeneralCategory/
        [HttpGet]
        public ActionResult Save()
        {
            List<GeneralCatagory> generalCatagories = manager.GetAll();
            ViewBag.GeneralCategoryList = generalCatagories;
            return View();
        }
        [HttpPost]
        public ActionResult Save(GeneralCatagory generalCatagory)
        {
            List<GeneralCatagory> generalCatagories = manager.GetAll();
            ViewBag.GeneralCategoryList = generalCatagories;

            bool IsCodeExist = manager.isCodeExist(generalCatagory.Code);
            if (IsCodeExist)
            {
                ViewBag.message = "Code is already exist !";
            }
            else
            {
                bool Save = manager.Add(generalCatagory);
                if (Save)
                {
                    ViewBag.message = "Save succesfull"; 
                }
                else
                {
                    ViewBag.message = "Save failed";
                }
               
            }
            return View();
        }
	}
}

AssetTrakingSystemApp/AssetTrakingSystemApp/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTrakingSystemApp.BLL;
using AssetTrakingSystemApp.Models;

namespace AssetTrakingSystemApp.Controllers
{
    public class SubCategoryController : Controller
    {
        SubCategoryManager subCategoryManager=new SubCategoryManager();
       GeneralCategoryManager generalCategoryManager=new GeneralCategoryManager();
        CategorySetupManager categorySetupManager=new CategorySetupManager();
        //
        // GET: /SubCategory/
        [HttpGet]
        public ActionResult Save()
        {
            List<GeneralCatagory> generalCatagories = generalCategoryManager.GetAll();
            ViewBag.GeneralcategoryList = generalCatagories;
            List<CategorySetup> categorySetups = categorySetupManager.GetAll();
            ViewBag.CategorySetupList = categorySetups;
            List<SubCategory> subCategories = subCategoryManager.GetAll();
            ViewBag.SubCategoryList = subCategories;
            return View();
        }
        [HttpPost]
        public ActionResult Save(SubCategory subCategory)
        {
            List<SubCategory> subCategories = subCategoryManager.GetAll();
            ViewBag.SubCategoryList = subCategories;
            List<GeneralCatagory> generalCatagories = generalCategoryManager.GetAll();
            ViewBag.GeneralcategoryList = generalCatagories;
             List<CategorySetup> categorySetups = categorySetupManager.GetAll();
            ViewBag.CategorySetupList = categorySetups;

            if (subCategory.Name == null || subCategory.Code == null || subCategory.CategorySetupId == 0 ||
                subCategory.GeneralCtegoryId == 0)
            {
                ViewBag.message = "input field is requird";
            }
            else
            {
                if (subCategory.Code.Length > 5)
                {
                    ViewBag.message = "Code lenth is greatr than 5 not allowed";
                }
                else
                {
                    bool IsCodeExist = subCategoryManager.isCodeExist(subCategory.Code);
                    if (IsCodeExist)
                    {
                        ViewBag.message = "code is already exist !";
                    }
                    else
                    {
                        bool Save = subCategoryManager.Add(subCategory);
                        if (Save)
                        {
                            ViewBag.message = "Save successfull";
                        }
                        else
                        {
                            ViewBag.message = "Save failed";
                        }
                    }
                }
            }

           
                
          
           
            return View();
        }

        public JsonResult GetCategorySetupIdByGeneralCategoryId(int generalCategoryId)
        {
            var CategorySetupIdLists = categorySetupManager.GetCategorySetupIdByGeneralCategoryId(generalCategoryId);
            return Json(CategorySetupIdLists, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSubCategoryIdByCategorySetupId(int CategorySetupId)
        {
            var subCategoriesLists = subCategoryManager.GetSubCategoryIdByCategorySetupId(CategorySetupId);
            return Json(subCategoriesLists, JsonRequestBehavior.AllowGet);
        }
	}
}

AssetTrakingSystemApp/AssetTrakingSystemApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Asset Managment System</title>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">  
    <div class="container">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Asset Managment System", "Index", "Home", null, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    <table>
        <tr>
            <th><li>@Html.ActionLink("Organization", "Save", "Organization")</li></th>
            <th><li>@Html.ActionLink("Organization Branch", "Save", "OrganizationBranch")</li></th>
            <th><li>@Html.ActionLink("Asset Location", "Save", "AssetLocation")</li></th>
            <th><li>@Html.ActionLink("general Category", "Save", "GeneralCategory")</li></th>
            <th><li>@Html.ActionLink("Category Setup", "Save", "CategorySetup")</li></th>
            <th><li>@Html.ActionLink("Sub category", "Save", "SubCategory")</li></th>
            <th><li>@Html.ActionLink("Product Category", "Save", "ProductCategoris")</li></th>
            <th><li>@Html.ActionLink("User Registration", "Save", "UserRegistration")</li></th>
           
        </tr>
    </table>
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>